name: Deploy to staging

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: worker

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers (Staging)
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.0
          run_install: true

      - name: Build
        run: "pnpm build"

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "worker"
